
#General settings
[general]
	#Is Enabled?
	enabled = true
	#Cost
	#Range: > -2147483648
	cost = 200
	#Is Starter Glyph?
	starter = false
	#The maximum number of times this glyph may appear in a single spell
	#Range: > 1
	per_spell_limit = 2147483647
	#The tier of the glyph
	#Range: 1 ~ 99
	glyph_tier = 2
	#Limits the number of times a given augment may be applied to a given effect
	#Example entry: "glyph_amplify=5"
	augment_limits = []
	#Prevents the given glyph from being used in the same spell as the given glyph
	#Example entry: "glyph_burst"
	invalid_combos = []
	#Enable a timer on the resize effects. Caster will return to original self when potion effect is removed.
	limitedMorphTime = false
	#Potion duration, in seconds
	#Range: > 0
	potion_time = 120
	#Extend time duration, in seconds
	#Range: > 0
	extend_time = 60
	#Morph will only allow you to transform is the target have less maximum hp than this value.
	#Range: > 20
	max_hp_morph = 100

